/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\lenovo\\Desktop\\zlz\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2986c4bf",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2986c4bf").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-53fab833",
    path: "/components/input.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53fab833").then(next)
    },
  },
  {
    name: "v-586e3d6e",
    path: "/components/grid.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-586e3d6e").then(next)
    },
  },
  {
    name: "v-7aed3489",
    path: "/components/button.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7aed3489").then(next)
    },
  },
  {
    name: "v-f43a7486",
    path: "/components/popover.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f43a7486").then(next)
    },
  },
  {
    name: "v-3d016989",
    path: "/components/layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d016989").then(next)
    },
  },
  {
    name: "v-3aba1c49",
    path: "/components/tabs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3aba1c49").then(next)
    },
  },
  {
    name: "v-ed7abf8e",
    path: "/components/toast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ed7abf8e").then(next)
    },
  },
  {
    name: "v-7469fb36",
    path: "/get-started/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7469fb36").then(next)
    },
  },
  {
    path: "/get-started/index.html",
    redirect: "/get-started/"
  },
  {
    name: "v-0fe756d8",
    path: "/install/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fe756d8").then(next)
    },
  },
  {
    path: "/install/index.html",
    redirect: "/install/"
  },
  {
    name: "v-3363610f",
    path: "/install/macos.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3363610f").then(next)
    },
  },
  {
    name: "v-0a0646cf",
    path: "/install/windows.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a0646cf").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]