/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "ZLZ UI",
  "description": "一个好用的UI框架",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "ZLZ UI 官网",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2986c4bf",
      "path": "/"
    },
    {
      "title": "组件",
      "frontmatter": {
        "title": "组件"
      },
      "regularPath": "/components/",
      "relativePath": "components/README.md",
      "key": "v-280c17a2",
      "path": "/components/"
    },
    {
      "title": "Button",
      "frontmatter": {
        "title": "Button"
      },
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-7aed3489",
      "path": "/components/button.html"
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/get-started/",
      "relativePath": "get-started/README.md",
      "key": "v-7469fb36",
      "path": "/get-started/"
    },
    {
      "title": "安装",
      "frontmatter": {
        "title": "安装"
      },
      "regularPath": "/install/",
      "relativePath": "install/README.md",
      "key": "v-0fe756d8",
      "path": "/install/"
    },
    {
      "title": "Windows",
      "frontmatter": {},
      "regularPath": "/install/windows.html",
      "relativePath": "install/windows.md",
      "key": "v-0a0646cf",
      "path": "/install/windows.html"
    },
    {
      "title": "MacOs",
      "frontmatter": {},
      "regularPath": "/install/macos.html",
      "relativePath": "install/macos.md",
      "key": "v-3363610f",
      "path": "/install/macos.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/guide/"
      },
      {
        "text": "交流",
        "link": "https://google.com"
      }
    ],
    "sidebar": [
      {
        "title": "入门",
        "children": [
          "/install/",
          "/get-started/"
        ]
      },
      {
        "title": "组件",
        "children": [
          "/components/button"
        ]
      }
    ]
  }
}