/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "ZLZ UI",
  "description": "一个好用的UI框架",
  "base": "/zlz/",
  "headTags": [],
  "pages": [
    {
      "title": "ZLZ UI 官网",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2986c4bf",
      "path": "/"
    },
    {
      "title": "Grid",
      "frontmatter": {
        "title": "Grid"
      },
      "regularPath": "/components/grid.html",
      "relativePath": "components/grid.md",
      "key": "v-586e3d6e",
      "path": "/components/grid.html"
    },
    {
      "title": "Button",
      "frontmatter": {
        "title": "Button"
      },
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-7aed3489",
      "path": "/components/button.html"
    },
    {
      "title": "Input",
      "frontmatter": {
        "title": "Input"
      },
      "regularPath": "/components/input.html",
      "relativePath": "components/input.md",
      "key": "v-53fab833",
      "path": "/components/input.html"
    },
    {
      "title": "Layout-布局",
      "frontmatter": {
        "title": "Layout-布局"
      },
      "regularPath": "/components/layout.html",
      "relativePath": "components/layout.md",
      "key": "v-3d016989",
      "path": "/components/layout.html"
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/get-started/",
      "relativePath": "get-started/README.md",
      "key": "v-7469fb36",
      "path": "/get-started/"
    },
    {
      "title": "Tabs-标签",
      "frontmatter": {
        "title": "Tabs-标签"
      },
      "regularPath": "/components/tabs.html",
      "relativePath": "components/tabs.md",
      "key": "v-3aba1c49",
      "path": "/components/tabs.html"
    },
    {
      "title": "Toast",
      "frontmatter": {
        "title": "Toast"
      },
      "regularPath": "/components/toast.html",
      "relativePath": "components/toast.md",
      "key": "v-ed7abf8e",
      "path": "/components/toast.html"
    },
    {
      "title": "Popover-弹出层",
      "frontmatter": {
        "title": "Popover-弹出层"
      },
      "regularPath": "/components/popover.html",
      "relativePath": "components/popover.md",
      "key": "v-f43a7486",
      "path": "/components/popover.html"
    },
    {
      "title": "安装",
      "frontmatter": {
        "title": "安装"
      },
      "regularPath": "/install/",
      "relativePath": "install/README.md",
      "key": "v-0fe756d8",
      "path": "/install/"
    },
    {
      "title": "MacOs",
      "frontmatter": {},
      "regularPath": "/install/macos.html",
      "relativePath": "install/macos.md",
      "key": "v-3363610f",
      "path": "/install/macos.html"
    },
    {
      "title": "Windows",
      "frontmatter": {},
      "regularPath": "/install/windows.html",
      "relativePath": "install/windows.md",
      "key": "v-0a0646cf",
      "path": "/install/windows.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/guide/"
      },
      {
        "text": "交流",
        "link": "https://google.com"
      }
    ],
    "sidebar": [
      {
        "title": "入门",
        "collapsable": false,
        "children": [
          "/install/",
          "/get-started/"
        ]
      },
      {
        "title": "组件",
        "collapsable": false,
        "children": [
          "/components/button",
          "/components/grid",
          "/components/input",
          "/components/layout",
          "/components/popover",
          "/components/tabs",
          "/components/toast"
        ]
      }
    ]
  }
}